[package]
name = "runer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7"
async-ffi = "0.4"
safer-ffi = "0.0.7"
tokio = {version ="1.18", features =["rt-multi-thread","macros"]}